name: 1st workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "Hello world"
      - name: print farewell
        run: echo "cya later alligator"