name: Output info
on: issues
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
# name: Output info
# on: workflow_dispatch
# jobs:
#   info:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Output gihub context
#         run: echo "${{ toJSON(github) }}"
